In [1]:
from warnings import filterwarnings
filterwarnings('ignore')

In [2]:
import os
os.chdir('D:/Datasets')

In [3]:
import pandas as pd
df=pd.read_csv('Cars93.csv')

In [4]:
df.head()

id Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0   1        Acura  Integra    Small       12.9   15.9       18.8        25   
1   2        Acura   Legend  Midsize       29.2   33.9       38.7        18   
2   3         Audi       90  Compact       25.9   29.1       32.3        20   
3   4         Audi      100  Midsize       30.8   37.7       44.6        19   
4   5          BMW     535i  Midsize       23.7   30.0       36.2        22   

   MPG.highway             AirBags  ... Passengers Length  Wheelbase  Width  \
0           31                None  ...          5    177        102     68   
1           25  Driver & Passenger  ...          5    195        115     71   
2           26         Driver only  ...          5    180        102     67   
3           26                 NaN  ...          6    193        106     70   
4           30         Driver only  ...          4    186        109     69   

   Turn.circle  Rear.seat.room Luggage.room  Weight   Origin           Make  
0           37            26.5         11.0    2705  non-USA  Acura Integra  
1           38            30.0         15.0    3560  non-USA   Acura Legend  
2           37            28.0         14.0    3375  non-USA        Audi 90  
3           37            31.0         17.0    3405  non-USA       Audi 100  
4           39            27.0         13.0    3640  non-USA       BMW 535i  

[5 rows x 28 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   id                  93 non-null     int64  
 1   Manufacturer        93 non-null     object 
 2   Model               93 non-null     object 
 3   Type                93 non-null     object 
 4   Min.Price           93 non-null     float64
 5   Price               93 non-null     float64
 6   Max.Price           93 non-null     float64
 7   MPG.city            93 non-null     int64  
 8   MPG.highway         93 non-null     int64  
 9   AirBags             89 non-null     object 
 10  DriveTrain          93 non-null     object 
 11  Cylinders           93 non-null     object 
 12  EngineSize          93 non-null     float64
 13  Horsepower          93 non-null     int64  
 14  RPM                 93 non-null     int64  
 15  Rev.per.mile        93 non-null     int64  
 16  Man.trans.

In [61]:
df.dtypes

id                      int64
Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city                int64
MPG.highway             int64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower              int64
RPM                     int64
Rev.per.mile            int64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers              int64
Length                  int64
Wheelbase               int64
Width                   int64
Turn.circle             int64
Rear.seat.room        float64
Luggage.room          float64
Weight                  int64
Origin                 object
Make                   object
dtype: object

In [6]:
df.columns

Index(['id', 'Manufacturer', 'Model', 'Type', 'Min.Price', 'Price',
       'Max.Price', 'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain',
       'Cylinders', 'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile',
       'Man.trans.avail', 'Fuel.tank.capacity', 'Passengers', 'Length',
       'Wheelbase', 'Width', 'Turn.circle', 'Rear.seat.room', 'Luggage.room',
       'Weight', 'Origin', 'Make'],
      dtype='object')

### seperate dependant and independant features
Weight ~ Remaining Features

In [7]:
X=df.drop(labels=['id','Weight'], axis=1)
Y=df[['Weight']]

In [8]:
X.shape

(93, 26)

In [9]:
X.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8        25   
1        Acura   Legend  Midsize       29.2   33.9       38.7        18   
2         Audi       90  Compact       25.9   29.1       32.3        20   
3         Audi      100  Midsize       30.8   37.7       44.6        19   
4          BMW     535i  Midsize       23.7   30.0       36.2        22   

   MPG.highway             AirBags DriveTrain  ... Fuel.tank.capacity  \
0           31                None      Front  ...               13.2   
1           25  Driver & Passenger      Front  ...               18.0   
2           26         Driver only      Front  ...               16.9   
3           26                 NaN      Front  ...               21.1   
4           30         Driver only       Rear  ...               21.1   

   Passengers  Length  Wheelbase  Width Turn.circle  Rear.seat.room  \
0           5     177        102     68          37            26.5   
1           5     195        115     71          38            30.0   
2           5     180        102     67          37            28.0   
3           6     193        106     70          37            31.0   
4           4     186        109     69          39            27.0   

   Luggage.room   Origin           Make  
0          11.0  non-USA  Acura Integra  
1          15.0  non-USA   Acura Legend  
2          14.0  non-USA        Audi 90  
3          17.0  non-USA       Audi 100  
4          13.0  non-USA       BMW 535i  

[5 rows x 26 columns]

In [10]:
Y.head()

Weight
0    2705
1    3560
2    3375
3    3405
4    3640

## Build SKlearn pipeline for preprocessing

In [11]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [12]:
#sepearte cat,con features
from PM8 import catconsep
cat,con = catconsep(X)

In [13]:
cat

['Manufacturer',
 'Model',
 'Type',
 'AirBags',
 'DriveTrain',
 'Cylinders',
 'Man.trans.avail',
 'Origin',
 'Make']

In [14]:
con

['Min.Price',
 'Price',
 'Max.Price',
 'MPG.city',
 'MPG.highway',
 'EngineSize',
 'Horsepower',
 'RPM',
 'Rev.per.mile',
 'Fuel.tank.capacity',
 'Passengers',
 'Length',
 'Wheelbase',
 'Width',
 'Turn.circle',
 'Rear.seat.room',
 'Luggage.room']

In [15]:
#Build Numeric Pipleine
num_pipe = Pipeline(steps=[('Imputer',SimpleImputer(strategy='mean')),
                          ('Standard',StandardScaler())])
#categorical
cat_pipe= Pipeline(steps=[('Imputer',SimpleImputer(strategy='most_frequent')),
                          ('OHE',OneHotEncoder(handle_unknown='ignore'))])
#combine
pre = ColumnTransformer([('num',num_pipe,con),
                        ('cat',cat_pipe,cat)])

In [16]:
X_pre = pre.fit_transform(X).toarray()
X_pre

array([[-0.48578741, -0.37572014, -0.28246529, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.38801699,  1.49784409,  1.53140881, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.00865782,  0.99822696,  0.94805231, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.66378585,  0.39452293,  0.16416702, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.53733279,  0.33207079,  0.14593713, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.88220476,  0.7484184 ,  0.60168439, ...,  0.        ,
         0.        ,  1.        ]])

In [17]:
cols = pre.get_feature_names_out()
cols

array(['num__Min.Price', 'num__Price', 'num__Max.Price', 'num__MPG.city',
       'num__MPG.highway', 'num__EngineSize', 'num__Horsepower',
       'num__RPM', 'num__Rev.per.mile', 'num__Fuel.tank.capacity',
       'num__Passengers', 'num__Length', 'num__Wheelbase', 'num__Width',
       'num__Turn.circle', 'num__Rear.seat.room', 'num__Luggage.room',
       'cat__Manufacturer_Acura', 'cat__Manufacturer_Audi',
       'cat__Manufacturer_BMW', 'cat__Manufacturer_Buick',
       'cat__Manufacturer_Cadillac', 'cat__Manufacturer_Chevrolet',
       'cat__Manufacturer_Chrylser', 'cat__Manufacturer_Chrysler',
       'cat__Manufacturer_Dodge', 'cat__Manufacturer_Eagle',
       'cat__Manufacturer_Ford', 'cat__Manufacturer_Geo',
       'cat__Manufacturer_Honda', 'cat__Manufacturer_Hyundai',
       'cat__Manufacturer_Infiniti', 'cat__Manufacturer_Lexus',
       'cat__Manufacturer_Lincoln', 'cat__Manufacturer_Mazda',
       'cat__Manufacturer_Mercedes-Benz', 'cat__Manufacturer_Mercury',
       'cat__Man

In [18]:
#create a Dataframe
X_pre = pd.DataFrame(X_pre,columns=cols)
X_pre.head()

num__Min.Price  num__Price  num__Max.Price  num__MPG.city  \
0       -0.485787   -0.375720       -0.282465       0.471312   
1        1.388017    1.497844        1.531409      -0.781032   
2        1.008658    0.998227        0.948052      -0.423219   
3        1.571949    1.893374        2.069191      -0.602126   
4        0.755752    1.091905        1.303535      -0.065407   

   num__MPG.highway  num__EngineSize  num__Horsepower  num__RPM  \
0          0.360925        -0.841022        -0.073484  1.717489   
1         -0.770514         0.515869         1.078322  0.369586   
2         -0.581941         0.128186         0.540813  0.369586   
3         -0.581941         0.128186         0.540813  0.369586   
4          0.172352         0.806631         1.231897  0.706562   

   num__Rev.per.mile  num__Fuel.tank.capacity  ...  cat__Make_Toyota Camry  \
0           1.129530                -1.062184  ...                     0.0   
1           0.005661                 0.409445  ...                     0.0   
2          -0.105713                 0.072197  ...                     0.0   
3           0.410659                 1.359872  ...                     0.0   
4           0.430909                 1.359872  ...                     0.0   

   cat__Make_Toyota Celica  cat__Make_Toyota Previa  cat__Make_Toyota Tercel  \
0                      0.0                      0.0                      0.0   
1                      0.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                      0.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   

   cat__Make_Volkswagen Corrado  cat__Make_Volkswagen Eurovan  \
0                           0.0                           0.0   
1                           0.0                           0.0   
2                           0.0                           0.0   
3                           0.0                           0.0   
4                           0.0                           0.0   

   cat__Make_Volkswagen Fox  cat__Make_Volkswagen Passat  cat__Make_Volvo 240  \
0                       0.0                          0.0                  0.0   
1                       0.0                          0.0                  0.0   
2                       0.0                          0.0                  0.0   
3                       0.0                          0.0                  0.0   
4                       0.0                          0.0                  0.0   

   cat__Make_Volvo 850  
0                  0.0  
1                  0.0  
2                  0.0  
3                  0.0  
4                  0.0  

[5 rows x 257 columns]

In [19]:
#train-test split
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X_pre,Y,test_size=0.2,random_state=75)

In [20]:
#build base model - linear regreassion
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(xtrain,ytrain)

LinearRegression()

In [21]:
#r2 score in training
r2_score_tr = model.score(xtrain,ytrain)
r2_score_tr

1.0

In [22]:
#r2 score in testing
r2_score_ts =model.score(xtest,ytest)
r2_score_ts

0.9296598900523217

## model evaluation with train-test split

In [23]:
from PM8 import evaluate_model
evaluate_model(xtrain,ytrain,xtest,ytest,model)

Training Scores :
MSE :  1.3553466117845218e-24
RMSE:  1.1641935456720767e-12
MAE :  9.279304051872443e-13
R2  :  1.0


Training Scores :
MSE :  18882.16925961675
RMSE:  137.41240577042797
MAE :  104.5210289091745
R2  :  0.9296598900523217


## cross validation

In [24]:
from sklearn.model_selection import cross_val_score

In [25]:
scores = cross_val_score(model,xtrain,ytrain,cv=5,scoring='neg_mean_squared_error')
scores

array([-71679.26141638, -40800.53121607, -23119.45703901, -13659.21779453,
       -12673.63032425])

In [26]:
scores.mean()           #mean squared error

-32386.41955804883

In [27]:
mae_score = cross_val_score(model,xtrain,ytrain,cv=5,scoring='neg_mean_absolute_error')
mae_score

array([-204.54814537, -140.86155153, -121.95344193, -103.74538915,
        -82.28883037])

In [28]:
mae_score.mean()

-130.67947166935988

In [29]:
r2_scores = cross_val_score(model,xtrain,ytrain,cv=5,scoring='r2')
r2_scores

array([0.82009642, 0.86297787, 0.92767319, 0.96864795, 0.94920898])

In [30]:
r2_scores.mean()

0.9057208824701523

In [31]:
neg_rmse = cross_val_score(model,xtrain,ytrain,cv=5,scoring='neg_root_mean_squared_error')
neg_rmse

array([-267.72982915, -201.99141372, -152.05083702, -116.87265632,
       -112.57721938])

In [32]:
neg_rmse.mean()

-170.2443911181337

In [33]:
## 10 Fold CV
r2_s2= cross_val_score(model,xtrain,ytrain,cv=10,scoring='r2')
r2_s2

array([0.71492667, 0.87629472, 0.95123049, 0.86306365, 0.90540077,
       0.90920551, 0.96618617, 0.9745386 , 0.9542096 , 0.88361753])

In [34]:
r2_s2.mean()

0.8998673716014338

## Ridge and Lasso Tuning
1. Alpha value : Hyperparameter
2. GridSearchCV

In [35]:
# alpha values
import numpy as np
alphas=np.arange(0.1,60,0.1)
alphas

array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
        1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
        2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
        4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,
        5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,
        6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,
        7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,
        8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9,
       10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ,
       11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1,
       12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2,
       13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3,
       14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15

# parameter
~~~
model = Ridge(alpha=value)
~~~

In [36]:
params = {'alpha':alphas}              #dictionary

In [37]:
## GridSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Ridge                     ##Ridge Model Evaluation
model1= Ridge()
gscv = GridSearchCV(model1,param_grid=params,cv=5,scoring='neg_root_mean_squared_error')
gscv.fit(xtrain,ytrain)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
        1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
        2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
        4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,
        5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,
        6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7....
       52.9, 53. , 53.1, 53.2, 53.3, 53.4, 53.5, 53.6, 53.7, 53.8, 53.9,
       54. , 54.1, 54.2, 54.3, 54.4, 54.5, 54.6, 54.7, 54.8, 54.9, 55. ,
       55.1, 55.2, 55.3, 55.4, 55.5, 55.6, 55.7, 55.8, 55.9, 56. , 56.1,
       56.2, 56.3, 56.4, 56.5, 56.6, 56.7, 56.8, 56.9, 57. , 57.1, 57.2,
       57.3, 57.4, 57.5, 57.6, 57.7, 57.8, 57.9, 58. , 58.1, 58.2, 58.3,
       58.4, 58.5, 58.6, 58.7, 58.8, 58.9, 59. , 59.1, 59.2, 59.3, 59.4,
       59.5, 59.6, 59.7, 59.8, 59.9])},
             scoring='neg_root_mean_squared_error')

In [38]:
gscv.best_params_

{'alpha': 9.9}

In [39]:
gscv.best_score_

-160.28972465205234

In [40]:
best_ridge= gscv.best_estimator_
best_ridge

Ridge(alpha=9.9)

In [41]:
# check model score in training
best_ridge.score(xtrain,ytrain)

0.9776869578562555

In [42]:
#Check score in testing
best_ridge.score(xtest,ytest)

0.9432697856831138

In [43]:
evaluate_model(xtrain,ytrain,xtest,ytest,best_ridge)

Training Scores :
MSE :  7714.028583635893
RMSE:  87.829542772554
MAE :  67.32196558321748
R2  :  0.9776869578562555


Training Scores :
MSE :  15228.71530429183
RMSE:  123.40468104691908
MAE :  97.85118932024395
R2  :  0.9432697856831138


In [44]:
## Tune Lasso Model
from sklearn.linear_model import Lasso
model2 = Lasso()
gscv2 = GridSearchCV(model2,param_grid=params,cv=5,scoring='neg_mean_squared_error')
gscv2.fit(xtrain,ytrain)

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
        1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
        2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
        4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,
        5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,
        6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7....
       52.9, 53. , 53.1, 53.2, 53.3, 53.4, 53.5, 53.6, 53.7, 53.8, 53.9,
       54. , 54.1, 54.2, 54.3, 54.4, 54.5, 54.6, 54.7, 54.8, 54.9, 55. ,
       55.1, 55.2, 55.3, 55.4, 55.5, 55.6, 55.7, 55.8, 55.9, 56. , 56.1,
       56.2, 56.3, 56.4, 56.5, 56.6, 56.7, 56.8, 56.9, 57. , 57.1, 57.2,
       57.3, 57.4, 57.5, 57.6, 57.7, 57.8, 57.9, 58. , 58.1, 58.2, 58.3,
       58.4, 58.5, 58.6, 58.7, 58.8, 58.9, 59. , 59.1, 59.2, 59.3, 59.4,
       59.5, 59.6, 59.7, 59.8, 59.9])},
             scoring='neg_mean_squared_error')

In [45]:
gscv2.best_params_

{'alpha': 6.1}

In [46]:
gscv2.best_score_

-28567.5697598572

In [47]:
best_lasso = gscv2.best_estimator_
best_lasso

Lasso(alpha=6.1)

In [48]:
best_lasso.score(xtrain,ytrain)

0.9662830858785725

In [49]:
best_lasso.score(xtest,ytest)

0.9204875032533849

In [50]:
evaluate_model(xtrain,ytrain,xtest,ytest,best_lasso)

Training Scores :
MSE :  11656.55662769435
RMSE:  107.96553444361005
MAE :  85.83076299252154
R2  :  0.9662830858785725


Training Scores :
MSE :  21344.413918901886
RMSE:  146.0972755355208
MAE :  117.14928826429829
R2  :  0.9204875032533849


In [51]:
# here I am selecting Ridge as my final model as testing score is higher

In [52]:
# Estimate car weights from new csv file
df2=pd.read_csv('sample.csv')
df2

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Audi      100  Midsize       30.8   37.7       44.6        19   
1      Pontiac  Sunbird  Compact        9.4   11.1       12.8        23   
2    Chevrolet   Lumina  Midsize       13.4   15.9       18.4        21   
3        Mazda     RX-7   Sporty       32.5   32.5       32.5        17   
4   Volkswagen      Fox    Small        8.7    9.1        9.5        25   

   MPG.highway      AirBags DriveTrain  ... Passengers  Length  Wheelbase  \
0           26          NaN      Front  ...          6     193        106   
1           31         None      Front  ...          5     181        101   
2           29         None      Front  ...          6     198        108   
3           25  Driver only       Rear  ...          2     169         96   
4           33         None      Front  ...          4     163         93   

   Width  Turn.circle Rear.seat.room  Luggage.room  Weight   Origin  \
0     70           37           31.0          17.0    3405  non-USA   
1     66           39           25.0          13.0    2575      USA   
2     71           40           28.5          16.0    3195      USA   
3     69           37            NaN           NaN    2895  non-USA   
4     63           34           26.0          10.0    2240  non-USA   

               Make  
0          Audi 100  
1   Pontiac Sunbird  
2  Chevrolet Lumina  
3        Mazda RX-7  
4    Volkswagen Fox  

[5 rows x 27 columns]

In [53]:
xnew = pre.transform(df2).toarray()
xnew

array([[ 1.57194871,  1.89337432,  2.06919057, ...,  0.        ,
         0.        ,  0.        ],
       [-0.88813804, -0.87533727, -0.829362  , ...,  0.        ,
         0.        ,  0.        ],
       [-0.42830874, -0.37572014, -0.31892507, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.76737617,  1.35212243,  0.9662822 , ...,  0.        ,
         0.        ,  0.        ],
       [-0.96860817, -1.08351107, -1.1301552 , ...,  0.        ,
         0.        ,  0.        ]])

In [54]:
xnew = pd.DataFrame(xnew,columns=cols)
xnew

num__Min.Price  num__Price  num__Max.Price  num__MPG.city  \
0        1.571949    1.893374        2.069191      -0.602126   
1       -0.888138   -0.875337       -0.829362       0.113500   
2       -0.428309   -0.375720       -0.318925      -0.244313   
3        1.767376    1.352122        0.966282      -0.959938   
4       -0.968608   -1.083511       -1.130155       0.471312   

   num__MPG.highway  num__EngineSize  num__Horsepower  num__RPM  \
0         -0.581941         0.128186         0.540813  0.369586   
1          0.360925        -0.647181        -0.649388 -0.135877   
2         -0.016221        -0.453339        -0.649388 -0.135877   
3         -0.770514        -1.325626         2.134145  2.054464   
4          0.738071        -0.841022        -1.206095  0.369586   

   num__Rev.per.mile  num__Fuel.tank.capacity  ...  cat__Make_Toyota Camry  \
0           0.410659                 1.359872  ...                     0.0   
1           0.673908                -0.449005  ...                     0.0   
2           0.532158                -0.050439  ...                     0.0   
3          -0.014589                 1.022624  ...                     0.0   
4           0.441034                -1.307455  ...                     0.0   

   cat__Make_Toyota Celica  cat__Make_Toyota Previa  cat__Make_Toyota Tercel  \
0                      0.0                      0.0                      0.0   
1                      0.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                      0.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   

   cat__Make_Volkswagen Corrado  cat__Make_Volkswagen Eurovan  \
0                           0.0                           0.0   
1                           0.0                           0.0   
2                           0.0                           0.0   
3                           0.0                           0.0   
4                           0.0                           0.0   

   cat__Make_Volkswagen Fox  cat__Make_Volkswagen Passat  cat__Make_Volvo 240  \
0                       0.0                          0.0                  0.0   
1                       0.0                          0.0                  0.0   
2                       0.0                          0.0                  0.0   
3                       0.0                          0.0                  0.0   
4                       1.0                          0.0                  0.0   

   cat__Make_Volvo 850  
0                  0.0  
1                  0.0  
2                  0.0  
3                  0.0  
4                  0.0  

[5 rows x 257 columns]

In [55]:
## predict final weights for new cars

In [56]:
preds= best_ridge.predict(xnew)
preds

array([[3452.41392031],
       [2699.82456135],
       [3135.54103592],
       [2994.13613136],
       [2261.85655446]])

In [58]:
df3 = df2[['Manufacturer','Model']]
df3

Manufacturer    Model
0         Audi      100
1      Pontiac  Sunbird
2    Chevrolet   Lumina
3        Mazda     RX-7
4   Volkswagen      Fox

In [59]:
df3['pred_Weights'] = preds
df3

Manufacturer    Model  pred_Weights
0         Audi      100   3452.413920
1      Pontiac  Sunbird   2699.824561
2    Chevrolet   Lumina   3135.541036
3        Mazda     RX-7   2994.136131
4   Volkswagen      Fox   2261.856554

In [60]:
df3.to_csv('Cars_predicted.csv',index=False)    #save file in csv